export default function Contenido (){
    return(
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate, fuga doloremque velit iusto voluptatem, debitis eaque repellendus quos eius veniam, quasi reiciendis unde maiores. Ducimus at ullam facilis consequatur veritatis!
    Inventore omnis reiciendis similique optio, veniam quisquam dignissimos, adipisci quo magnam nesciunt magni ea, blanditiis et. Laborum totam, quo error, eveniet nobis laudantium quis recusandae, temporibus maxime cum culpa. Voluptates?
    Cupiditate iure ea nam incidunt debitis, illo, corporis temporibus modi quaerat obcaecati dolorem suscipit dolorum, repudiandae fugiat nostrum totam autem assumenda perspiciatis eveniet recusandae est iste eius. Quibusdam, explicabo dicta.
    Odit, repellat ipsam! Autem accusamus soluta et illo quia esse ab quos tempore veritatis exercitationem dolor expedita, perferendis ratione optio praesentium labore. Molestias unde dolorum dolore natus obcaecati, sint magnam?
    Repellendus ut quo facilis voluptatum modi, eius officiis praesentium error cum quis cupiditate expedita quia libero voluptas amet doloribus ad aspernatur excepturi, mollitia explicabo eveniet vero nisi veritatis obcaecati. Reprehenderit.
    Recusandae totam alias quam? Nam similique quasi iste totam magnam, laboriosam quibusdam reiciendis quam alias nemo natus maxime ipsam blanditiis architecto amet facilis autem sed modi expedita, dolorum sapiente. Natus.
    Vero impedit placeat earum esse assumenda. Ad accusamus quidem consequatur modi, quam repellat iste laudantium blanditiis ab. Dolore odio qui autem reprehenderit. Eius corrupti sequi consectetur. Modi, magni natus. Sint.
    Numquam soluta dolore mollitia praesentium placeat labore quam cum cumque cupiditate voluptatem impedit rerum saepe, accusamus incidunt ab aliquam ea accusantium nobis doloribus dicta molestias ullam atque debitis corrupti! Vero.
    Id minus maiores tenetur fuga placeat consequatur magnam voluptatum ex ut esse quaerat dolorum asperiores obcaecati quasi, nisi ullam debitis! Non eum laborum assumenda dolore eligendi doloremque culpa molestiae quae.
    Aut aliquam debitis non exercitationem sunt dicta, beatae ullam! Quod rem minus odio. Culpa id nulla quisquam atque aperiam, labore at dolore debitis delectus illum. Doloribus cumque excepturi numquam consequatur.
    Laborum, unde? Similique corporis blanditiis quia delectus maiores quos aperiam, perferendis vitae iure officiis aliquam velit perspiciatis laborum nostrum, ut, earum error dolor consequuntur reprehenderit repellendus neque obcaecati tempore! Deleniti.
    Quasi ipsam dolore dolorum minus, eum, optio architecto, fuga animi perferendis dolor suscipit quo! Exercitationem accusamus quaerat laboriosam nisi autem minima id, voluptate nostrum nihil doloribus, magnam dicta adipisci. Ratione.
    Quia sequi culpa magnam consectetur molestiae repellendus et earum laudantium reiciendis, numquam quis atque mollitia, fugit suscipit aliquid nam nostrum ad. Qui laudantium quia aliquam veniam eius et quasi rerum.
    Possimus, vero facilis? Laudantium animi ut ipsam pariatur vitae eius temporibus eligendi, fuga et veritatis itaque tempora neque provident nemo mollitia impedit molestias corporis eos. Quibusdam accusamus ipsum et similique.
    Quia mollitia dolor quas vero velit natus labore eius hic odio illo exercitationem, inventore rerum temporibus quam reprehenderit nisi porro? Excepturi, eligendi? Voluptates commodi, pariatur id illo molestiae qui velit.
    Qui facere labore minus quod, odit, fugiat exercitationem molestiae, quis voluptatum vel laborum doloribus perferendis nihil. Tempore earum nisi voluptatibus ullam ad esse laboriosam nihil necessitatibus qui at? Necessitatibus, dolor!
    Nesciunt, tenetur perferendis ea earum modi tempore sapiente nihil. Culpa in atque sequi itaque necessitatibus, cupiditate beatae quas rerum quis, expedita, ea alias repudiandae ipsa laudantium voluptas ipsam reiciendis perferendis.
    Reiciendis sunt obcaecati quam aliquid animi repellat veniam consequuntur deserunt eos architecto ad libero voluptas consectetur laboriosam autem vitae laborum repudiandae provident, iste, reprehenderit suscipit cupiditate! Accusamus cumque alias fugit?
    Architecto placeat illum porro ex harum et accusamus est laudantium obcaecati eveniet a magni cupiditate facere quas suscipit voluptates nisi corporis expedita, necessitatibus, animi distinctio doloremque, rem blanditiis dolorem? Minus?
    Rem ea nostrum pariatur laudantium eveniet, accusamus consectetur distinctio beatae in autem accusantium eius nesciunt soluta expedita molestiae nulla sunt minima ullam consequuntur enim deserunt modi perspiciatis rerum. Animi, esse!</p>
    )
}